---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argo-acm-jccm
  namespace: openshift-gitops
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - argo-acm-jccm
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
